name: CI
on: [push]
jobs:
  lint:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: src/emscripten
    steps:
      - uses: actions/checkout@v2
      - run: npm install prettier
      - run: npm run format:check
      - run: npm run shellcheck

  test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: src/emscripten
    strategy:
      matrix:
        wasm_simd: ['yes', 'no']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: docker-compose pull

      - name: Extract bench signature from git log
        run: echo "sign_ref=$(bash misc/git-log-bench-signature.sh)" >> $GITHUB_ENV

      - name: Build Stockfish
        run: >
          DOCKER_USER=$(id -u):$(id -g) docker-compose run emscripten
          make -C .. emscripten_build ARCH=wasm wasm_simd=${{ matrix.wasm_simd }}

      - name: Run server for headless testing
        run: npm install serve && (npm run serve & sleep 5)

  test-embedded-nnue:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: src/emscripten
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: docker-compose pull emscripten node

      - name: Extract bench signature from git log
        run: echo "sign_ref=$(bash misc/git-log-bench-signature.sh)" >> $GITHUB_ENV

      - name: Extract default net name
        run: echo "default_net=$(make -C .. net | grep "Default net" | awk '{ print $NF }')" >> $GITHUB_ENV

      - name: Build Stockfish
        run: >
          DOCKER_USER=$(id -u):$(id -g) docker-compose run emscripten
          make -C .. emscripten_build ARCH=wasm embedded_nnue=yes

      #- name: Verify stockfish.wasm < 2MB
      #  run: >
      #    [ $(wc -c public/stockfish.wasm | awk '{ print $1 }') -lt 2000000 ]

      - uses: actions/upload-artifact@v3
        with:
          name: embedded-nnue
          path: src/emscripten/public/stockfish*